### PR TITLE
Added version 1.0 of Ubuntu skin

### PR DESCRIPTION
**Pull request by darshandsoni**
Dem aubergines and oranges be cray. Here is Vanilla Ubuntu!

### CODE REVIEW

**Comment by darshandsoni** [comment]
Not ready for pull! I hadn't synced my repo yet.

**Comment by darshandsoni** [comment]
Alright... hopefully all good!

**Comment by darshandsoni** [comment]
Patched the index.html file too to make future skinning easier. If you look at the proposed changes, you will see that it adds a separate class to the input field and button, making them easier to skin.

**Comment by dohliam** [comment]
Looks great! Why don't we add some bold to make the font more readable against the background?

**Comment by darshandsoni** [comment]
Body font is now white to be more readable.

**Comment by dohliam** [comment]
Wow, that looks amazing. What an improvement! Merging ASAP

**Pull request merged**
